### ISSUE TITLE
Latest version on NPM

### ISSUE THREAD

**Issue by domguinard** [melanke/Watch.JS#100]
I was trying to find watch.js on NPM and I suppose it's watchjs however the version on NPM is listed as 0.0.0 https://www.npmjs.com/package/watchjs any chances of pushing the latest version? 

Thanks a lot!

**Comment by domguinard** [comment]
Any news on that? We'd love to include watch.js in a node opensource project (https://github.com/webofthings/webofthings.js), if you don't have the time to push it to NPM let us know and we'll help.

**Comment by melanke** [comment]
`npm install melanke-watchjs`

**Comment by domguinard** [comment]
great, thanks a lot!
