### ISSUE TITLE
how to install it with npm @type

### ISSUE THREAD

**Issue by JasonWuuu** [melanke/Watch.JS#104]
in angular2 project ,I can't  install it with below command, any idea, thanks in advance

npm install --save @types/melanke-watchjs

**Comment by melanke** [comment]
I don't know, never heard about `@types` before

**Comment by JasonWuuu** [comment]
the watchjs is great for some case,  many thanks , does it own defined type for watchjs,  e.g watchjs.d.ts  for typescript 2.0

**Comment by melanke** [comment]
It haven't, but please, if you know how to do it, please send me a push request :)
