### ISSUE TITLE
Use Object.prototype.watch if possible

### ISSUE THREAD

**Issue by frankred** [melanke/Watch.JS#114]
Dear maintainer,

I just looked at the code of WATCH.JS and did not find the use of https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/watch . Is there a reason why this has not beeing used? Maybe if browser supports it, it should be used instead of polling.

Edit:

Or maybe overwrite all the setter of the objects: https://gist.github.com/eligrey/384583

What do you think?

**Comment by melanke** [comment]
This method is deprecated and should not be used
