### ISSUE TITLE
Is this alive?

### ISSUE THREAD

**Issue by robsoncombr** [melanke/Watch.JS#117]
Hello,

I do not see updates like since 7 months ago, is this project live? Is it stable?

Thanks.

**Comment by robsoncombr** [comment]
Zombie.

**Comment by englishextra** [comment]
I guess:

a) It's summer time
b) arrive, ractive, siteglass and many more other libs, not alternatives, but do the job
c) native https://developer.mozilla.org/en/docs/Web/API/MutationObserver
