### ISSUE TITLE
how can i get the fully qualified property name in callback even

### ISSUE THREAD

**Issue by tariqmatech** [melanke/Watch.JS#119]
trying to use if for two way binding, the beautiful thing about this one is I can use my ajax response as is. don't want to add bulky frameworks for two way binding. 

please let me know how can i get the fully qualified property name in callback event so i can update DOM objects in my html with the newly modified value.

**Comment by qualityking** [comment]
hi @tariqmatech  i am trying the same and looking for the full property name myself, anyluck ?

**Comment by melanke** [comment]
Duplicate of #77
