### ISSUE TITLE
Uncaught TypeError: Cannot set property 'x' of undefined

### ISSUE THREAD

**Issue by noisiak** [melanke/Watch.JS#128]
Hello. I just got this error and I am not sure what is causing it. I am working with the Three.js library.

It happens when I watch for the "position" attribute from my object. The position attribute it's a vector with 3 properties (x,y,z).

The error happens after I call this:
`watch(object, "position", function(){
            // console.log("object changed!");
});`

Any idea of what could be the cause of this error?

Here is the log:
<img width="381" alt="screen shot 2018-09-23 at 23 14 15" src="https://user-images.githubusercontent.com/38593917/45935891-8d2f2480-bf86-11e8-8ca2-5d4b036eb7ba.png">

Curiously, the watcher itself does work as intended, so I not sure why the error is happening.

**Comment by swindex** [comment]
Should be watching properties of HTML elements and other non-plain objects?

**Comment by noisiak** [comment]
Not really. I just need it to watch the "position" of the "object".

**Comment by noisiak** [comment]
I found my mistake: you need to give the full path of property: object.position, instead of just "position"
