### ISSUE TITLE
Method unwatch() for all watchers

### ISSUE THREAD

**Issue by cadavre** [melanke/Watch.JS#38]
For now we can only unwatch object like in example: https://github.com/melanke/Watch.JS#remove-a-watcher.

It's only working with selected params. But when watching for all changes - we cannot unwatch whole object.

**Comment by rmahoney-bl** [comment]
Any word on getting unwatch to completely stop watching all attributes of a watched object?

**Comment by khaledosman** [comment]
+1

**Comment by cadavre** [comment]
I guess this library was dropped due to existence of JS frameworks like AngularJS and its watchers. I also suggest to move to such frameworks.
