### ISSUE TITLE
Observe Array Index

### ISSUE THREAD

**Issue by rummelj** [melanke/Watch.JS#75]
Hi! Thanks for the great library. Is it somehow possible to observe a certain index of an Array?

Example:
`var arr = ["foo", "bar", "baz"]`
`WatchJS.watch(arr, 1, callback)`

Expected Behaviour:
`arr[0] = "newFoo" // callback is NOT called`
`arr[1] = "newBar" // callback IS called`
`arr[2] = "newBaz" // callback is NOT called`

Current Behaviour:
Callback is never called

Best
Johannes

**Comment by melanke** [comment]
`WatchJS.watch(arr[1], callback)` will not work.
but it will work if you change the array like this: 
```
var index = 2;
arr.splice(index, 1, 'newValue'); // 1 is for deleting one item at that position before adding a new
```
