### ISSUE TITLE
Cannot watch localStorage

### ISSUE THREAD

**Issue by gymbry** [melanke/Watch.JS#79]
Tried:

> localStorage.setItem('name, 'gymbry');
> watch(localStorage, 'name', function () { alert() });
> localStorage.setItem('name, 'stuff');
> which returns nothing.

Tried:

> localStorage.watch('name', function () { alert() });

which says "Undefined is not a function".
Also tried:

> watch(JSON.parse(localStorage), 'name', function () { alert() });

and

> JSON.parse(localStorage).watch('name', function () { alert() });

which returns error "Uncaught SyntaxError: Unexpected token o".
This same error is returned when using Object.observe().

**Comment by ng-webtools** [comment]
Did you ever solve this @gymbry ? Outside of some dirty checking, I'm running out of options for a use case like this.

**Comment by melanke** [comment]
Yeah, that will not work, localStorage is not a plain object
