### ISSUE TITLE
Adding two watchers to the same property make watchers fire multiple times

### ISSUE THREAD

**Issue by fedevegili** [melanke/Watch.JS#80]
Hello, I'm having a problem using WatchJS 1.3.0. Whenever I add two watchers or more to the same property, watchers are fired multiple times.

Simulation:
http://jsfiddle.net/gow3eLd4/

Open your console and hit "run", you'll see that "first" and "second" were fired twice instead of once.

Another simulation:
http://jsfiddle.net/kc0tf8zy/
With four watchers, everything is fired four times.

Am I missing something or is it really a bug?
Thank you.

**Comment by gunins** [comment]
Does this fix is applied to master?

**Comment by xwisdom** [comment]
Yes it is

**Comment by robsoncombr** [comment]
Is this supposed to be closed?
