### ISSUE TITLE
Watch.js doubts ?

### ISSUE THREAD

**Issue by vinothwindows47** [melanke/Watch.JS#92]
1 . I am using ember framework in client development . Is watch.js is equal to ember observes ?

2 . If I watch multiple objects in my application, the application performance will go to slow ?

3 . Is it MIT License ?

4 . Is it compatible for all browsers ?

**Comment by herrjemand** [comment]
@vinothwindows47 

1. Yes it is similar to Ember observers.
2. If you use same instance of observer, only one timer will be utilized, so it is not too heave performance utilized.
3. ![_178](https://cloud.githubusercontent.com/assets/1636116/21580286/d29afc70-d04e-11e6-847e-030a7f3424fd.png)
4. ![_179](https://cloud.githubusercontent.com/assets/1636116/21580292/f91f92de-d04e-11e6-9023-aacb525f7366.png)

P.S. Most of repositories have Readme.md that has all of the answers:
![_177](https://cloud.githubusercontent.com/assets/1636116/21580294/3009da0c-d04f-11e6-898b-5b6e1d0c7084.png)
