### ISSUE TITLE
Object.observe' is deprecated

### ISSUE THREAD

**Issue by danyj** [melanke/Watch.JS#95]
Just started getting the msg  in latest Chrome 

```
Object.observe' is deprecated and will be removed in M50
```

are we going to need a workaround ?

**Comment by Fyrebox** [comment]
There seems to be some fallbacks already in the code. I downloaded version 51 of Chromium ( from [https://commondatastorage.googleapis.com/chromium-browser-continuous/index.html?prefix=Mac/381067/](https://commondatastorage.googleapis.com/chromium-browser-continuous/index.html?prefix=Mac/381067/) for MAC ) and tested my app. The objects are still being watched

**Comment by melanke** [comment]
We are using `Object.defineProperty`, no more `Object.observe`
