### ISSUE TITLE
Get location where change occurred?

### ISSUE THREAD

**Issue by AvengerD** [melanke/Watch.JS#97]
Is there any way to determine, where a change of an attribute has been initiated (which line in which Javascript file)????

I get reported the attribute change, but I need to know, where this change comes from.

**Comment by melanke** [comment]
this is an interesting feature but it was not implemented

**Comment by beta-tank** [comment]
@AvengerD you cant try use https://www.stacktracejs.com or answers from here http://stackoverflow.com/questions/591857/how-can-i-get-a-javascript-stack-trace-when-i-throw-an-exception in your callback to determine who change variable value.
